# Generated by Django 5.0.4 on 2024-09-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('ip_public', models.GenericIPAddressField(null=True)),
                ('os_version', models.CharField(max_length=255, null=True)),
                ('processor', models.CharField(max_length=255, null=True)),
                ('ram', models.FloatField(help_text='RAM capacity in MB', null=True)),
                ('storage', models.FloatField(help_text='Disk space in GB', null=True)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('console_user', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefenderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_events', to='app1.computer')),
            ],
        ),
        migrations.CreateModel(
            name='DefenderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus_mode', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('antivirus_mode_ts', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('platform_ts', models.DateTimeField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_ts', models.DateTimeField(blank=True, null=True)),
                ('security_intelligence', models.CharField(blank=True, max_length=50, null=True)),
                ('security_intelligence_ts', models.DateTimeField(blank=True, null=True)),
                ('last_quick_scan_ts', models.DateTimeField(blank=True, null=True)),
                ('last_full_scan_ts', models.DateTimeField(blank=True, null=True)),
                ('last_event_ts', models.DateTimeField(blank=True, null=True)),
                ('computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defender_status', to='app1.computer')),
            ],
        ),
    ]
