# Generated by Django 5.0.4 on 2024-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='console_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.FloatField(blank=True, help_text='RAM capacity in MB', null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.FloatField(blank=True, help_text='Disk space in GB', null=True),
        ),
    ]
