# Generated by Django 5.0.4 on 2024-12-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_computer_console_user_alter_computer_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='laps',
            field=models.CharField(blank=True, help_text='Local Admin Password', max_length=50, null=True),
        ),
    ]
