# Generated by Django 5.0.4 on 2025-01-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_computer_laps'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='encryption_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('PREPPED', 'Prepped'), ('ASSIGNED', 'Assigned'), ('TERMED_NOT_RETURNED', 'Termed Not Returned'), ('RETIRED', 'Retired'), ('IT_STORAGE', 'IT Storage'), ('WAITING_RETURN', 'Waiting for Return'), ('LOCATION_UNKNOWN', 'Location Unknown')], default='PREPPED', max_length=30),
        ),
        migrations.AddField(
            model_name='computer',
            name='warranty_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
