# Generated by Django 5.0.4 on 2025-01-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_computer_asset_tag_computer_assigned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('CHANGE_ME', 'Change me'), ('PREPPED', 'Prepped'), ('ASSIGNED', 'Assigned'), ('TERMED_NOT_RETURNED', 'Termed Not Returned'), ('RETIRED', 'Retired'), ('IT_STORAGE', 'IT Storage'), ('WAITING_RETURN', 'Waiting for Return'), ('LOCATION_UNKNOWN', 'Location Unknown')], default='CHANGE_ME', max_length=30),
        ),
    ]
