# Generated by Django 5.0.4 on 2025-02-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_computer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('CHANGE_ME', 'Change Me'), ('PREPPED', 'Prepped'), ('ASSIGNED', 'Assigned'), ('TERMED_NOT_RETURNED', 'Termed Not Returned'), ('RETIRED', 'Retired'), ('IT_STORAGE', 'IT Storage'), ('WAITING_RETURN', 'Waiting for Return'), ('LOCATION_UNKNOWN', 'Location Unknown')], default='CHANGE_ME', max_length=30),
        ),
    ]
