# Generated by Django 5.0.4 on 2025-02-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_computer_ip_alter_computer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip_public',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
