# Generated by Django 5.0.4 on 2025-04-08 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_computer_ip_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='encryption_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Serial must be alphanumeric and can only contain _, -', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
