# Generated by Django 5.0.4 on 2025-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_computer_encryption_enabled_alter_computer_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='encryption_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
