# Generated by Django 5.0.4 on 2025-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_computer_encryption_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='encryption_enabled',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
