# Generated by Django 5.0.4 on 2025-11-06 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_computer_encryption_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='encryption_enabled',
            field=models.BooleanField(default=None, null=True, verbose_name='Encrypted'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Serial must be alphanumeric and can only contain _, -', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
